kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: weave-privileged
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - privileged
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: weave-privileged
roleRef:
  kind: ClusterRole
  name: weave-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Authorize specific service accounts:
  - kind: ServiceAccount
    name: weave-scope
    namespace: weave